<?php
    $proofs = Mage::helper('printproof')->getProofsForOrder();
?>
<div class="entry-edit">
    <div class="entry-edit-head">
        <h4><?php echo $this->__('Create New Proof') ?></h4>
    </div>
    <div class="fieldset printproof-create-fieldset">
        <form action="<?php echo $this->getUrl('printproofadmin/admin/createProof') ?>" method="post" enctype="multipart/form-data">
            <input type="hidden" name="order_id" value="<?php echo $this->getOrderId() ?>" />
            <input type="hidden" name="form_key" value="<?php echo $this->getFormKey() ?>" />
            <table cellspacing="0" class="form-list">
                <tbody>
                    <tr>
                        <td class="label">
                            <label><?php echo $this->__('Item') ?></label>
                        </td>
                        <td class="value">
                            <select name="item_id">
                            <?php foreach ($this->getOrder()->getAllItems() as $item): ?>
                                <option value="<?php echo $item->getId() ?>"><?php echo $item->getName() ?> (#<?php echo $item->getId() ?>)</option>
                            <?php endforeach; ?>
                            </select>
                        </td>
                    </tr>
                    <tr>
                        <td class="label">
                            <label><?php echo $this->__('Comment') ?></label>
                        </td>
                        <td class="value">
                            <textarea name="comment"></textarea>
                        </td>
                    </tr>
                    <tr>
                        <td class="label">
                            <label><?php echo $this->__('Attachment') ?></label>
                        </td>
                        <td class="value">
                            <input type="file" name="attachment" />
                        </td>
                    </tr>
                    <tr>
                        <td class="label">&nbsp;</td>
                        <td class="value">
                            <button type="submit" class="button"><?php echo $this->__('Create New Proof') ?></button>
                        </td>
                    </tr>
                </tbody>
            </table>
        </form>
    </div>
</div>
<div class="entry-edit">
    <div class="entry-edit-head">
        <h4><?php echo $this->__('Printing Proofs') ?></h4>
    </div>
    <div class="fieldset printproof-fieldset">
    <?php if ($proofs->count()): ?>
        <?php foreach ($proofs as $proof): ?>
            <?php $comments = $proof->getCommentList(); ?>
            <div class="printproof">
                <div class="printproof-col printproof-img">
                    <?php echo Mage::helper('printproof')->getProofImage($proof); ?>
                </div>
                <div class="printproof-col">
                    <p>
                        Item: <strong>#<?php echo $proof->getItemId() ?></strong><br>
                        Status: <strong class="status-<?php echo $proof->getStatus() ?>"><?php echo $proof->getStatus() ?> <?php echo $proof->getApprovedDate() ? 'on ' . date('jS M Y H:i', strtotime($proof->getApprovedDate())) : '' ?></strong>
                    </p>
                    <?php foreach (array_reverse($comments) as $comment): ?>
                        <div class="printproof-comment">
                            <p>
                                <strong><?php echo $comment['name'] ?></strong><br/>
                                <em><?php echo $comment['date'] ?></em>
                            </p>
                            <p><?php echo $comment['comment'] ?></p>
                            <?php if(isset($comment['attachment'])): ?>
                                <a href="<?php echo Mage::helper('edge/image')->getImage($comment['attachment']) ?>">
                                    <?php echo Mage::helper('edge/image')->getImage($comment['attachment']) ?>
                                </a>
                            <?php endif; ?>
                        </div>
                    <?php endforeach; ?>
                </div>
                <div class="printproof-clear">&nbsp;</div>
            </div>
        <?php endforeach; ?>
    <?php else: ?>
        <p><?php echo $this->__('This order has no proofs.') ?></p>
    <?php endif; ?>
    </div>
</div>