<?php
    $proofs = Mage::helper('printproof')->getProofsForOrder();
?>
<div class="entry-edit">
    <div class="entry-edit-head">
        <h4><?php echo $this->__('Printing Proofs') ?></h4>
    </div>
    <div class="fieldset">
    <?php if ($proofs->count()): ?>
        <?php foreach ($proofs as $proof): ?>
            <div class="printproof">
                <div class="printproof-status">
                    Status: <strong><?php echo $proof->getStatus() ?></strong>
                </div>
                <?php foreach ($proof->getCommentList() as $comment): ?>
                    <div class="printproof-comment">
                        <p>
                            <strong><?php echo $comment->getName() ?></strong><br/>
                            <em><?php echo $comment->getDate() ?></em>
                        </p>
                        <p><?php echo $comment->getComment() ?></p>
                        <a href="<?php echo $comment->getAttachmentUrl() ?>">
                            <?php echo $comment->getAttachment() ?>
                        </a>
                    </div>
                <?php endforeach; ?>
                <form id="printproof_reply_<?php echo $proof->getId() ?>" action="<?php echo $proof->getReplyUrl(true) ?>" method="POST" enctype="multipart/form-data" class="printproof-reply-form">
                    <input type="hidden" name="proof_id" value="<?php echo $proof->getId() ?>"/>
                    <input type="hidden" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>"/>
                    <ul class="form-list">
                        <li class="wide">
                            <textarea name="comment" id="comment_<?php echo $proof->getId() ?>" class="textarea required-entry" style="width: 100%"></textarea>
                        </li>
                        <li class="wide">
                            <input type="file" name="attachment_<?php echo $proof->getId() ?>" />                    
                        </li>
                    </ul>
                    <button type="submit" class="button"><?php echo Mage::helper('printproof')->__('Reply') ?></button>
                </form>
            </div>
        <?php endforeach; ?>
    <?php else: ?>
        <p><?php echo $this->__('This order has no proofs.') ?></p>
    <?php endif; ?>
    </div>
</div>
<div class="entry-edit">
    <div class="entry-edit-head">
        <h4><?php echo $this->__('Create New Proof') ?></h4>
    </div>
    <div class="fieldset">
        <form action="<?php echo $this->getUrl('printproofadmin/adminhtml_proof/createProof') ?>" method="post" enctype="multipart/form-data">
            <input type="hidden" name="order_id" value="<?php echo $this->getOrderId() ?>" />
            <input type="hidden" name="form_key" value="<?php echo $this->getFormKey() ?>" />
            <table cellspacing="0" class="form-list">
                <tbody>
                    <tr>
                        <td class="label">
                            <label><?php echo $this->__('Comment') ?></label>
                        </td>
                        <td class="value">
                            <textarea name="comment"></textarea>
                        </td>
                    </tr>
                    <tr>
                        <td class="label">
                            <label><?php echo $this->__('Attachment') ?></label>
                        </td>
                        <td class="value">
                            <input type="file" name="attachment" />
                        </td>
                    </tr>
                    <tr>
                        <td class="label">&nbsp;</td>
                        <td class="value">
                            <button type="submit" class="button"><?php echo $this->__('Create New Proof') ?></button>
                        </td>
                    </tr>
                </tbody>
            </table>
        </form>
    </div>
</div>